
#Where to store data for id-to-name mapping for features like genres, platforms, etc.
feature_maps_folder: "feature_id_lookups/"


#Where to store data for junction tables that map game ids to feature ids like genres, platforms, etc.
junctions_folder: "feature_junctions/"

junctions_fp_template: "game_to_{field}.json"

#Where to store raw and cleaned games data
games_folder: "games_data/"

#File paths for raw and cleaned games data
games_raw_fp: "raw_games.json"
games_clean_fp: "clean_games.json"


#Where to store raw and cleaned multiplayer modes data
multiplayer_modes_folder: "multiplayer_modes_data/"

#File paths for raw and cleaned multiplayer modes data
multiplayer_modes_raw_fp: "raw_multiplayer_modes.json"
multiplayer_modes_clean_fp: "clean_multiplayer_modes.json"


#File path template for feature id-to-name mapping files
feature_maps_fp_template: "{field}_names.json"


#Default parameters for API requests
games_request_params:
  fields: "name,game_modes,genres,platforms,rating,updated_at,first_release_date"
  filters: "where multiplayer_modes != null & updated_at > {last_updated}; limit {limit}; offset {offset};"

games_dtypes:
  name: 'string'
  rating: 'float64'
  updated_at: 'datetime64[s]'
  first_release_date: 'datetime64[s]'




feature_names_request_params:
  fields: "id,name,updated_at"
  filters: "where updated_at > {last_updated}; limit {limit}; offset {offset};"

multiplayer_modes_request_params:
  fields: "id,game,dropin,campaigncoop,offlinecoop,offlinecoopmax,offlinemax,onlinecoop,onlinecoopmax,onlinemax,platform,splitscreen"
  filters: "limit {limit}; offset {offset};"

multiplayer_modes_dtypes:
  id: 'int64'
  game: 'int64'
  campaigncoop: 'bool'
  offlinecoop: 'bool'
  offlinecoop: 'bool'
  offlinecoopmax: 'int64'
  offlinemax: 'int64'
  onlinecoop: 'bool'
  onlinecoopmax: 'int64'
  onlinemax: 'int64'
  splitscreen: 'bool'

multiplayer_modes_conflicts: 
  online:
    coop_column: 'onlinecoop'
    coop_max_column: 'onlinecoopmax'
    max_column: 'onlinemax'
  offline: 
    coop_column: 'offlinecoop'
    coop_max_column: 'offlinecoopmax'
    max_column: 'offlinemax'

multiplayer_modes_outlier_columns: ['onlinecoop', 'onlinecoopmax', 'onlinemax','offlinecoop', 'offlinecoopmax', 'offlinemax']

multiplayer_cols: ['Co-operative', 'Split screen']



api_request_limit : 500

multiplayer_outlier_threshold_online : 5000
multiplayer_outlier_threshold_offline : 100